### ISSUE TITLE
Utterances appears on site.com/stg but not on site.com

### ISSUE THREAD

**Issue by pascalandy** [utterance/utterances#105]
Hi,
I'm using Utterances on my personal blog on it's all good. I decided to use on a second website (static). 

I'm confused about this behavior. Both have the exact same code. 

- **Works here** — https://play-with-ghost.com/stg
- **Does not work here** — https://play-with-ghost.com/

Do you see why something would prevent the loading on the root of my site?

Thanks!

**Comment by jdanyow** [comment]
The utterances script tag on `https://play-with-ghost.com` has `issue-term="pathname"`. This page has no pathname component on the url.  The other page works because the the pathname component of the url is `/stg`.

Maybe utterances should replace blank pathname components with `/`.  In the meantime, you could create an issue manually, then remove the `issue-term` attribute and use `issue-number="...your issue's number..."`.

**Comment by pascalandy** [comment]
Thanks again for you support Jeremy. You temporary fix works perfectly. Cheers!
