### ISSUE TITLE
Feature: Headless mode

### ISSUE THREAD

**Issue by samselikoff** [utterance/utterances#114]
I would love to use this, if I could completely customize the rendering! I'd love to just use utterances to set up the auth & data fetching & deal with the rate limiting, but then be able to style the comments according to my site.

**Comment by vitordino** [comment]
+1 on this

**Comment by jdanyow** [comment]
After thinking about this a bit more, I've decided to close. I do think this would be a useful feature. There have been some similar requests as well, for example #36.

The blocker is the OAuth flow, issue creation and comment creation would all be Utterances branded due to the way GitHub apps work. Abuse of this feature could lead users to deauthorize the app, or worse, if GitHub stepped in. This would break folks who are using the "stock" version of utterances.

Hopefully this makes sense. Forking the project is an option. It's super cheap to run. Even at my scale it's $5 a month. You'd be able to run on the free dev tier of cloudflare workers.
