### ISSUE TITLE
3rd party cookies and token 401

### ISSUE THREAD

**Issue by StefanoChiodino** [utterance/utterances#123]
Is there any way to handle more gracefully browsers blocking 3rd party cookies? Until I enable utterance domain cookies in chrome the token request is getting 401 and the "login to comment" functionality is broken!

Thanks!

**Comment by mu29** [comment]
I faced this issue too. Can't sign in on Safari, but Chrome works fine.

**Comment by lahvak** [comment]
I get the same thing in Chromium.  Cannot sign in on any site using utterances

**Comment by yawpitch** [comment]
Same problem on iOS Safari with `Settings > Safari > Prevent Cross-Site Tracking` enabled. Which explains why I _can_ comment on the utteranc.es site, just nowhere else.

**Comment by jinfagang** [comment]
@mutoe @mu29  Chrome also have this issue:

```
utterances.dc2b6d26.js:1 POST https://api.utteranc.es/token 401
```

![image](https://user-images.githubusercontent.com/21303438/55865068-431f3080-5bb0-11e9-9029-66d8c98a4fd8.png)


Hoping author can help us fix this issue. @utterances-bot

**Comment by yawpitch** [comment]
I’m thinking the only solution to this might be to self-host utterances, as that _should_ make the cookie first party, at least.

**Comment by StefanoChiodino** [comment]
Self hosting may do it, as long as it's the same domain. Also 3rd party cookie blocking is default on iOS and Safari alike, and this doesn't seem to be a problem when testing in localhost, which makes this even worse.

**Comment by yawpitch** [comment]
Since my goal was a static _without_ server-side hosting, the self-host option is less than ideal. I’m also not sure if the cookie is ultimately coming from the (probably Azure-hosted) app or the (could be GitHub Pages hosted) JS mentioned in the minimal instructions in #42.

I’m kind of surprised this hasn’t come up _a lot_ by now. Looks like Disqus has gotten around it by getting the browsers to whitelist their cookies — which seems crazy since blocking most of the privacy-defeating shenanigans of Disqus is the whole motivation for me even looking at utterances — but I can’t imagine that happening here any time soon.

**Comment by wildraid** [comment]
I have the same problem. It looks like any user of Google Chrome is now affected.

**Comment by Dog2puppy** [comment]
This problem also occurs on Safari.

**Comment by lahvak** [comment]
I added [a post](https://space.lahvak.space/2019/04/09/how-to-comment-on-this-blog/) on my site instructing visitors to enable third party cookies from `utteranc.es` if they want to comment.  It is not an ideal solution, but I figured out that since commenting requires a github account anyway, people who will want to comment should be able to figure out how to enable third party cookies for a particular site in their browser.

**Comment by samsalisbury** [comment]
Anyone think there might be a way to make utteranc.es work without needing a cookie at all? Or is this just the way it has to be, so we'd better get used to it and self-host?

**Comment by garritfra** [comment]
Anyone still experiencing this? I still get 401ed.
