### ISSUE TITLE
Dynamically change theme?

### ISSUE THREAD

**Issue by robbiet480** [utterance/utterances#170]
Is there any way to change the theme from JavaScript? I see the configurator sends a message like `{type: "set-theme", theme: "github-dark"}` using `postMessage` but am unable to get this working on my own site. For now, I'll have to resort to reloading utterances whenever the user changes the theme. Would be great if this was actually supported though.

**Comment by jdanyow** [comment]
I think it works. The key is to use pass `https://utteranc.es` in the second arg of the `postMessage` call (the `targetOrigin` parameter) because the message is targeted at the utterances iframe. 

```js
const message = {
  type: 'set-theme',
  theme: 'github-dark'
};
var utterances = document.querySelector('iframe');
utterances.contentWindow.postMessage(message, 'https://utteranc.es');
```

**Comment by Jakeler** [comment]
How to do it on page load? I want to restore theme settings from localstorage with JS.
The problem is that nothing happens, apparently because the message comes to early. So far i have tried running it from a event listener on window `DOMContentLoaded` or `load`, which did not work: 
```
main.js:44 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://utteranc.es') does not match the recipient window's origin ('http://myurl.xyz')
```
Then even from an iframe.onload function, it shows no error, but nothing changes. 
It works in my tests only if triggered later manually.

**Comment by jdanyow** [comment]
@Jakeler try this:
```ts
// wait for utterances to load and send it's first message.
addEventListener('message', event => {
  if (event.origin !== 'https://utteranc.es') {
    return;
  }
  const message = {
    type: 'set-theme',
    theme: 'github-dark'
  };
  const utterances = document.querySelector('iframe').contentWindow; // try event.source instead
  utterances.postMessage(message, 'https://utteranc.es');
});
