### ISSUE TITLE
Request - Anonymous comments

### ISSUE THREAD

**Issue by agarrharr** [utterance/utterances#20]
I wonder if there could be a way to allow anonymous comments. This could allow someone to comment who doesn't have a GitHub account. Maybe it would trigger a GitHub bot to post the comment on their behalf.

**Comment by jdanyow** [comment]
I considered this when doing the initial design for utterances. Opted not to add this feature for a couple reasons:

1. Concern that this would facilitate spam comments
2. The bot account or app could get reported/banned, breaking the feature

Going to close this because I don't think I'll ever add this feature. I appreciate the feedback and would be willing to support you in implementing this in a fork of the project.

**Comment by benwiley4000** [comment]
I'd also like this feature - I'd like to use something like utterances under the condition it doesn't lock users into needing to have an account with a specific third party service (GitHub). I appreciate your concerns.. One way to get around the spam potential could be to require moderator approval on all non-authenticated comments, and save draft comments that haven't yet been approved into a subdirectory on the repo.

**Comment by thomaslevesque** [comment]
>     1. Concern that this would facilitate spam comments

Unfortunately, even requiring a registered Github user doesn't block spam entirely... I just got this:

![image](https://user-images.githubusercontent.com/1864281/81542885-a5c79a80-9375-11ea-98cf-449653364fbe.png)
