### ISSUE TITLE
privacy issue

### ISSUE THREAD

**Issue by nlitsme** [utterance/utterances#264]
I noticed that for every page load, a lot of info about my blog is being sent to https://utteranc.es/utterances.html Why does the utterances.es domain need to know which posts exist on my blog?

I did read the comment at [issue 37](https://github.com/utterance/utterances/issues/37), there is no mention of this there.

Also, looking at the https://github.com/utterances-bot contributions list, it seems utterances does collect quite a lot of data on users, all conveniently in one place.

willem

**Comment by jdanyow** [comment]
**Utterances does not store any data about your site or it's visitors.**

Here's how it works:

1. You add the following to your site template:
    ```html
    <script src="https://utteranc.es/client.js"
        repo="[ENTER REPO HERE]"
        issue-term="pathname"
        theme="github-light"
        crossorigin="anonymous"
        async>
    </script>
    ```
2. The client.js script reads the page's title, description, url and passes them via the query string to the utterances component (an iframe). For example, here's the url that is generated to render the utterances component on my own blog.
    ```
    https://utteranc.es/utterances.html?src=https%3A%2F%2Futteranc.es%2Fclient.js&repo=jdanyow%2Fblog-comments&issue-term=pathname&url=https%3A%2F%2Fdanyow.net%2Fusing-github-issues-for-blog-comments%2F&origin=https%3A%2F%2Fdanyow.net&pathname=using-github-issues-for-blog-comments%2F&title=Using%20GitHub%20Issues%20for%20Blog%20Comments&og%3Atitle=Using%20GitHub%20Issues%20for%20Blog%20Comments
    ```
    Here's the client.ts code which gather's the information about the page:
    https://github.com/utterance/utterances/blob/ad0d56cba7106720ce56de8f0a3fbc39ccc29b3c/src/client.ts#L30-L40

3. The utterances component uses the page title/description/url (based on the mapping you chose) to create the GitHub issue when the first user posts a comment.

That's it. There's no database, no analytics, nothing.

Regarding @utterances-bot, it only exists to create the GitHub issues. We cannot create the issues using your blog readers accounts because this would give them the ability to delete the issue, and all the comments along with it.

Let me know if you have any further questions/concerns.
