### ISSUE TITLE
Some possible modifications?

### ISSUE THREAD

**Issue by cjpelaezrivas** [utterance/utterances#33]
I've been testing this tool for a while. It looks great and it's incredible simple, but I have some ideas that could be interesting to have as a blogger.

First, would it be possible to hide the 'new comment' section using, for example, a parameter? I would like to show only the current comments, but I you want to write a new comment, you have to go to the GitHub issue page.

In this case, it would be great if using another parameter you could show a button to open the Github issue page. I mean, a meaningful button that links to the same page that opens the current number of comments link. It could be valid too if it were somethig like [1] at the begining and/or the end of the comments section.

Lastly, I would like to modify slightly the style of the `iframe` content. Maybe an optional paramater (yes, one more) to send the changes in the style of the generated page, like font size, background color, maximum width, etc.

These are only some ideas that I have been thinking about while using this tool. For me is fully functional right now - *Nice work!* -, but I would love to have some of these features at some point.

Thanks.

[1] 
![image](https://user-images.githubusercontent.com/17297773/39049414-ac45302c-44a1-11e8-8862-2b4c18230eee.png)

**Comment by jdanyow** [comment]
@cjpelaezrivas thanks for the feedback. Could you share some more information about your scenario? I'm interested in hearing why you'd rather users post comments via the GitHub site.  [On docs.microsoft.com](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library) (scroll to the bottom) we added an option to open issues on GitHub directly. It's a fairly new feature, I haven't seen the reports on how much it's used yet.

Custom styling was something I had considered early on in the project but hadn't implemented because I was concerned about the [security implications](https://stackoverflow.com/a/3613162/725866). I'm still interested in exploring custom css or at least providing some additional themes (dark theme perhaps).

**Comment by jdanyow** [comment]
just following up on the background-color aspect: utterances will now inherit the host page's background color.

**Comment by jdanyow** [comment]
closing, there hasn't been a lot of folks interested in the button to comment directly on github.
