### ISSUE TITLE
Is utterances SEO friendly? 

### ISSUE THREAD

**Issue by kaknut** [utterance/utterances#330]

**Comment by jdanyow** [comment]
Great question. The comments are not server-side rendered. They are not indexed by search engines. It's not feasible to use server-side rendering because the server would quickly saturate the rate limit imposed by github. By using client side rendering the rate limit is spread across each visitor's ip address.

**Comment by ghassanmas** [comment]
@jdanyow what if we added a flag so utterance rendered only at specific build. And the server doesn't has to continuously  rebuild the page, say for example once every 24 hours or 48 hours and only **_if the comments/issue has been updated since the last build_**

**Comment by swyxio** [comment]
i improved things a bit by lazy loading utterances based on the viewport btw.

https://github.com/sw-yx/swyxkit/pull/167
