### ISSUE TITLE
Does utterances require login to show the comments?

### ISSUE THREAD

**Issue by sheldonhull** [utterance/utterances#353]
Noticed today that it just showed "4 comments" without displaying until I "logged in to comment". 

Is this expected behavior or could something else like adblock or an incorrect configuration cause that to occur?

**Comment by bender2k14** [comment]
Did the problem persist over a refresh?

**Comment by sheldonhull** [comment]
Not sure. I just opened in incognito mode. 
Try accessing [this url](https://www.sheldonhull.com/blog/asciidoc-distributed-docs-as-code/) and feel free to reopen this issue if you observe the issue. Otherwise I'll close it.

**Comment by bender2k14** [comment]
It appears to be working correctly in incognito mode for me.
![2020-07-09_20-38-26_158_chrome](https://user-images.githubusercontent.com/34664007/87106973-3ad6fa80-c224-11ea-8943-556ac39debce.png)

**Comment by LazyRen** [comment]
Can we reopen this issue?
![signin](https://user-images.githubusercontent.com/8989837/102595611-37448980-415b-11eb-8fcc-f3558491ad01.png)

In all utterances posts, I need to login to see comments, otherwise it only show how many comments are there.

This is the only reason preventing me from migrating to utterances from disqus.

**Comment by LazyRen** [comment]
> Not sure. I just opened in incognito mode.
> Try accessing [this url](https://www.sheldonhull.com/blog/asciidoc-distributed-docs-as-code/) and feel free to reopen this issue if you observe the issue. Otherwise I'll close it.

Can we reopen this issue?
![signin](https://user-images.githubusercontent.com/8989837/102595611-37448980-415b-11eb-8fcc-f3558491ad01.png)

In all utterances posts, I need to login to see comments, otherwise it only show how many comments are there.

This is the only reason preventing me from migrating to utterances from disqus.
