### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by jlelse** [utterance/utterances#37]
I'm using utterances on a couple of sites, but is it GDPR compliant? I wasn't able to find any signs.. and isn't it necessary to offer anonymous comments?

**Comment by jdanyow** [comment]
> 🚨 Disclaimer: I'm not a lawyer, and I'm not making any guarantees or accepting any liability here.

That said, great question, important question. 👍

I believe utterances **is** GDPR compliant because the utterances widget does not store any data at all. No user data, no comment data, nothing. Everything is stored in the GitHub issues and comments.

There is google analytics on the utterances on the *[home page](https://utteranc.es) only*. There is no tracking whatsoever on the widget that you include on your blog pages.

I will check with some experts on my team @MicrosoftDocs- we're using a similar GitHub issues based feedback system on https://docs.microsoft.com. To my knowledge it is GDPR compliant. I don't know of any material implementation differences that would impact GDPR.

Here are a couple links related to GitHub's GDPR compliance:
- https://github.community/t5/How-to-use-Git-and-GitHub/GDPR-and-GitHub/td-p/6098
- https://blog.github.com/2018-04-19-updates-to-our-privacy-statement-and-terms-of-service/
