### ISSUE TITLE
2 different pages have the same comments

### ISSUE THREAD

**Issue by rain-1** [utterance/utterances#46]
2 different pages have the same comments

* https://rain-1.github.io/shell
* https://rain-1.github.io/shell-2

there is only 1 issue https://github.com/rain-1/rain-1.github.io/issues/3 and both pages display it. I guess it's because of the "-2" bit?

**Comment by jdanyow** [comment]
you're using the *issue title contains pathname* option.  The pathname portion of https://rain-1.github.io/shell is `shell`. Since the issue search is "contains" the issue titled [shell-2](https://github.com/rain-1/rain-1.github.io/issues/3) is picked up.

Try changing https://rain-1.github.io/shell to https://rain-1.github.io/shell-1
