### ISSUE TITLE
Migrate comments from disqus

### ISSUE THREAD

**Issue by jdanyow** [utterance/utterances#7]

**Comment by JuergenGutsch** [comment]
I just published a small console tool to migrate Disqus XML to GitHub issues:
https://github.com/JuergenGutsch/disqus-to-github-issues

**Comment by JuergenGutsch** [comment]
Hi @lazywinadmin 
* **History**: I kept the history by migrating the comments in the right order. But the hierarchy is gone because the GitHub issue comments are a flat list
* **Date & Author**: Actually there is no way to map the Disqus users to GutHub users and you are not able to set the actual issue comment date. I placed the original autor name and the original name into the comment.

The result looks like this: https://github.com/JuergenGutsch/blog/issues/117
It's not really the nicest solution, but fine for me.

**Comment by jdanyow** [comment]
closing as @JuergenGutsch provided a solution

**Comment by daattali** [comment]
@JuergenGutsch Thanks for your work on that! Could you add a small README that has instructions on how to run your tool?

**Comment by JuergenGutsch** [comment]
@daattali Thanks! Sure. I'll do that.

**Comment by daattali** [comment]
Thank you! I'm considering adding this commenting platform to my github theme [beautiful-jekyll](https://github.com/daattali/beautiful-jekyll) but I wanted to ensure existing users can easily migrate their comments

**Comment by JuergenGutsch** [comment]
I just added a small README :-)

**Comment by eallion** [comment]
awesome!!

**Comment by eallion** [comment]
> I just added a small README :-)

Thanks! Can you add a BIG README? Step by step...

**Comment by leimao** [comment]
> Hi @lazywinadmin
> 
> * **History**: I kept the history by migrating the comments in the right order. But the hierarchy is gone because the GitHub issue comments are a flat list
> * **Date & Author**: Actually there is no way to map the Disqus users to GutHub users and you are not able to set the actual issue comment date. I placed the original autor name and the original name into the comment.
> 
> The result looks like this: [JuergenGutsch/blog#117](https://github.com/JuergenGutsch/blog/issues/117) It's not really the nicest solution, but fine for me.

Thank you very much for the example.

![Screenshot from 2022-07-19 08-06-52](https://user-images.githubusercontent.com/17606112/179784246-64b2969f-1c14-4566-bdea-377c7b9035d2.png)

Due to the limitation of GitHub based comment system that there are no anonymous user, after migration, the comments from other users do not look great to me. I am hesitating between paying Disqus and migrating to other comment systems.
